[package]
name = "supernova_audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Audio engine for Supernova Engine"

[dependencies]
supernova_core = { workspace = true }
parking_lot    = { workspace = true }
log            = { workspace = true }
ahash          = { workspace = true }
serde          = { workspace = true }
