[package]
name = "supernova_editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Supernova Editor"

[lib]
name = "supernova_editor"
path = "src/lib.rs"

[[bin]]
name = "supernova-editor"
path = "src/main.rs"

[dependencies]
supernova_engine   = { workspace = true }
supernova_core     = { workspace = true }
supernova_math     = { workspace = true }
supernova_renderer = { workspace = true }
supernova_scene    = { workspace = true }
supernova_assets   = { workspace = true }
egui               = { workspace = true }
egui-wgpu          = { workspace = true }
log                = { workspace = true }
env_logger         = { workspace = true }
winit              = { workspace = true }
wgpu               = { workspace = true }
crossbeam-channel  = { workspace = true }
pollster           = { workspace = true }
bytemuck           = { workspace = true }
